apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    app.kubernetes.io/component: nexus
    app.kubernetes.io/instance: nexus
  name: nexus
  namespace: oraex-cicd
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deployment: nexus
  sessionAffinity: None
  type: ClusterIP